In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("housing.csv")
df['income_cat'] = pd.cut(df['median_income'],bins=[0,1.5,3.0,4.5,6.0,np.inf],labels=[1,2,3,4,5]) #making another column for making bins

## Training & Testing Data

## Stratified Shuffle Split

In [7]:
#Making training and testing data to representative data of population

In [8]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
for train_index,test_index in split.split(df,df['income_cat']):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

In [9]:
#that impressive sari income categories aa rahi he
#aisa nahi he all income catgory in training and not test(same vice versa)
#that why we use strata suffle

In [10]:
strat_train_set

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,income_cat
12655,-121.46,38.52,29.0,3873.0,797.0,2237.0,706.0,2.1736,72100.0,INLAND,2
15502,-117.23,33.09,7.0,5320.0,855.0,2015.0,768.0,6.3373,279600.0,NEAR OCEAN,5
2908,-119.04,35.37,44.0,1618.0,310.0,667.0,300.0,2.8750,82700.0,INLAND,2
14053,-117.13,32.75,24.0,1877.0,519.0,898.0,483.0,2.2264,112500.0,NEAR OCEAN,2
20496,-118.70,34.28,27.0,3536.0,646.0,1837.0,580.0,4.4964,238300.0,<1H OCEAN,3
...,...,...,...,...,...,...,...,...,...,...,...
15174,-117.07,33.03,14.0,6665.0,1231.0,2026.0,1001.0,5.0900,268500.0,<1H OCEAN,4
12661,-121.42,38.51,15.0,7901.0,1422.0,4769.0,1418.0,2.8139,90400.0,INLAND,2
19263,-122.72,38.44,48.0,707.0,166.0,458.0,172.0,3.1797,140400.0,<1H OCEAN,3
19140,-122.70,38.31,14.0,3155.0,580.0,1208.0,501.0,4.1964,258100.0,<1H OCEAN,3
19773,-122.14,39.97,27.0,1079.0,222.0,625.0,197.0,3.1319,62700.0,INLAND,3

In [11]:
strat_test_set

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,income_cat
5241,-118.39,34.12,29.0,6447.0,1012.0,2184.0,960.0,8.2816,500001.0,<1H OCEAN,5
17352,-120.42,34.89,24.0,2020.0,307.0,855.0,283.0,5.0099,162500.0,<1H OCEAN,4
3505,-118.45,34.25,36.0,1453.0,270.0,808.0,275.0,4.3839,204600.0,<1H OCEAN,3
7777,-118.10,33.91,35.0,1653.0,325.0,1072.0,301.0,3.2708,159700.0,<1H OCEAN,3
14155,-117.07,32.77,38.0,3779.0,614.0,1495.0,614.0,4.3529,184000.0,NEAR OCEAN,3
...,...,...,...,...,...,...,...,...,...,...,...
12182,-117.29,33.72,19.0,2248.0,427.0,1207.0,368.0,2.8170,110000.0,<1H OCEAN,2
7275,-118.24,33.99,33.0,885.0,294.0,1270.0,282.0,2.1615,118800.0,<1H OCEAN,2
17223,-119.72,34.44,43.0,1781.0,342.0,663.0,358.0,4.7000,293800.0,<1H OCEAN,4
10786,-117.91,33.63,30.0,2071.0,412.0,1081.0,412.0,4.9125,335700.0,<1H OCEAN,4
3965,-118.56,34.19,36.0,2600.0,441.0,1246.0,426.0,4.1111,215600.0,<1H OCEAN,3

In [12]:
# remove the income cat column
for sett in (strat_train_set,strat_test_set):
    sett.drop("income_cat",axis=1,inplace=True)

In [13]:
df = strat_train_set.copy()

In [14]:
df
strat_train_set

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
12655,-121.46,38.52,29.0,3873.0,797.0,2237.0,706.0,2.1736,72100.0,INLAND
15502,-117.23,33.09,7.0,5320.0,855.0,2015.0,768.0,6.3373,279600.0,NEAR OCEAN
2908,-119.04,35.37,44.0,1618.0,310.0,667.0,300.0,2.8750,82700.0,INLAND
14053,-117.13,32.75,24.0,1877.0,519.0,898.0,483.0,2.2264,112500.0,NEAR OCEAN
20496,-118.70,34.28,27.0,3536.0,646.0,1837.0,580.0,4.4964,238300.0,<1H OCEAN
...,...,...,...,...,...,...,...,...,...,...
15174,-117.07,33.03,14.0,6665.0,1231.0,2026.0,1001.0,5.0900,268500.0,<1H OCEAN
12661,-121.42,38.51,15.0,7901.0,1422.0,4769.0,1418.0,2.8139,90400.0,INLAND
19263,-122.72,38.44,48.0,707.0,166.0,458.0,172.0,3.1797,140400.0,<1H OCEAN
19140,-122.70,38.31,14.0,3155.0,580.0,1208.0,501.0,4.1964,258100.0,<1H OCEAN
19773,-122.14,39.97,27.0,1079.0,222.0,625.0,197.0,3.1319,62700.0,INLAND

In [15]:
#mistakly strat_train_set in median_house_value deleted so taking from df
housing_labels = df["median_house_value"].copy()
housing_labels

12655     72100.0
15502    279600.0
2908      82700.0
14053    112500.0
20496    238300.0
           ...
15174    268500.0
12661     90400.0
19263    140400.0
19140    258100.0
19773     62700.0
Name: median_house_value, Length: 16512, dtype: float64

In [16]:
from sklearn.impute import SimpleImputer

In [17]:
imputer = SimpleImputer(strategy="median")#mean,most_frequent,most_frequent,constant

In [18]:
housing_num = df.select_dtypes(include=[np.number])

In [19]:
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [20]:
#imputer: ready to replace  missing value with median

In [21]:
imputer.statistics_

array([-1.18510e+02,  3.42600e+01,  2.90000e+01,  2.11900e+03,
        4.33000e+02,  1.16400e+03,  4.08000e+02,  3.54155e+00,
        1.79500e+05])

In [22]:
x = imputer.transform(housing_num)

In [23]:
x

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  7.0600e+02,
         2.1736e+00,  7.2100e+04],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  7.6800e+02,
         6.3373e+00,  2.7960e+05],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  3.0000e+02,
         2.8750e+00,  8.2700e+04],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  1.7200e+02,
         3.1797e+00,  1.4040e+05],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  5.0100e+02,
         4.1964e+00,  2.5810e+05],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  1.9700e+02,
         3.1319e+00,  6.2700e+04]])

In [102]:
housing = pd.DataFrame(x,columns=housing_num.columns,index=housing_num.index)
housing['ocean_proximity']=  df['ocean_proximity']
housing = housing[['ocean_proximity']]

In [108]:
print(set(housing['ocean_proximity']))
housing

{'NEAR OCEAN', '<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY'}

      ocean_proximity
12655          INLAND
15502      NEAR OCEAN
2908           INLAND
14053      NEAR OCEAN
20496       <1H OCEAN
...               ...
15174       <1H OCEAN
12661          INLAND
19263       <1H OCEAN
19140       <1H OCEAN
19773          INLAND

[16512 rows x 1 columns]

## Ordianl Encoding

In [63]:
from sklearn.preprocessing import OrdinalEncoder

In [73]:
ordinal_encoder = OrdinalEncoder()
housing_cat = ordinal_encoder.fit_transform(housing)

In [75]:
housing_cat

array([[2.390e+02, 5.690e+02, 2.800e+01, ..., 1.815e+03, 2.920e+02,
        1.000e+00],
       [6.620e+02, 5.500e+01, 6.000e+00, ..., 9.519e+03, 2.337e+03,
        4.000e+00],
       [4.810e+02, 2.730e+02, 4.300e+01, ..., 3.475e+03, 3.960e+02,
        1.000e+00],
       ...,
       [1.130e+02, 5.610e+02, 4.700e+01, ..., 4.239e+03, 9.710e+02,
        0.000e+00],
       [1.150e+02, 5.480e+02, 1.300e+01, ..., 6.403e+03, 2.133e+03,
        0.000e+00],
       [1.710e+02, 7.010e+02, 2.600e+01, ..., 4.107e+03, 2.000e+02,
        1.000e+00]])

In [79]:
housing_cat = pd.DataFrame(housing_cat,columns=housing.columns,index=housing.index)
housing_cat

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
12655,239.0,569.0,28.0,3555.0,795.0,2167.0,704.0,1815.0,292.0,1.0
15502,662.0,55.0,6.0,4411.0,853.0,1965.0,766.0,9519.0,2337.0,4.0
2908,481.0,273.0,43.0,1410.0,308.0,625.0,298.0,3475.0,396.0,1.0
14053,672.0,21.0,23.0,1669.0,517.0,856.0,481.0,1959.0,694.0,4.0
20496,515.0,174.0,26.0,3269.0,644.0,1791.0,578.0,6883.0,1942.0,0.0
...,...,...,...,...,...,...,...,...,...,...
15174,678.0,49.0,13.0,4852.0,1208.0,1976.0,996.0,7805.0,2232.0,0.0
12661,243.0,568.0,14.0,5072.0,1354.0,3353.0,1322.0,3341.0,473.0,1.0
19263,113.0,561.0,47.0,518.0,164.0,416.0,170.0,4239.0,971.0,0.0
19140,115.0,548.0,13.0,2924.0,578.0,1166.0,499.0,6403.0,2133.0,0.0
19773,171.0,701.0,26.0,877.0,220.0,583.0,195.0,4107.0,200.0,1.0

## One Hot Encoding

In [86]:
from sklearn.preprocessing import OneHotEncoder

In [90]:
ordinal_encoder = OneHotEncoder()

In [110]:
housing_cat = ordinal_encoder.fit_transform(housing)
ordinal_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [112]:
housing_cat.toarray()

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [114]:
# to back on dataframe

In [118]:
housing_cat = pd.DataFrame(housing_cat.toarray(),columns = ['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],index=housing.index)
housing_cat

       <1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
12655        0.0     1.0     0.0       0.0         0.0
15502        0.0     0.0     0.0       0.0         1.0
2908         0.0     1.0     0.0       0.0         0.0
14053        0.0     0.0     0.0       0.0         1.0
20496        1.0     0.0     0.0       0.0         0.0
...          ...     ...     ...       ...         ...
15174        1.0     0.0     0.0       0.0         0.0
12661        0.0     1.0     0.0       0.0         0.0
19263        1.0     0.0     0.0       0.0         0.0
19140        1.0     0.0     0.0       0.0         0.0
19773        0.0     1.0     0.0       0.0         0.0

[16512 rows x 5 columns]